---
name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  YAML-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
